name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
    - run: go build ./...
    - run: go test ./...
    - id: generate
      run: |
        go generate
        git diff --exit-code
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
    - uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9
      with:
        version: v2.2.2
