name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
      with:
        cache: true
    - run: go build ./...
    - run: go test ./...
    - id: generate
      run: |
        go generate
        git diff --exit-code
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
      with:
        cache: true
    - uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5
      with:
        version: v1.51.2
