name: Test
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
env:
  GO_VERSION: 1.x
  GOLANGCI_LINT_VERSION: 1.50.1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
      with:
        cache: true
        go-version: ${{ env.GO_VERSION }}
    - run: go build ./...
    - run: go test ./...
    - id: generate
      run: |
        go generate
        git diff --exit-code
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
      with:
        cache: true
        go-version: ${{ env.GO_VERSION }}
    - uses: golangci/golangci-lint-action@07db5389c99593f11ad7b44463c2d4233066a9b1
      with:
        version: v${{ env.GOLANGCI_LINT_VERSION }}
